config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books, only: [:index, :create] do
    collection do
      get 'search'
      post 'registration'
      patch 'req'
    end
  end
  root 'books#index'
end

app/models/book.rb
class Book < ActiveRecord::Base

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books

  def full_name
    return "#{family_name} #{first_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:first_name, :family_name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def create
    @book = Book.create(create_params)
  end

  def registration
    @book = Book.new(registration_params)
  end

  def req
    requester = current_user
    owner = User.find(params.require(:book)[:user_id])
    book = Book.find(params.require(:book)[:id])
    RequestMailer.request_email(requester, owner, book).deliver_now
    redirect_to :root
  end

  def search
    @books = []

    # キーワードが存在しない場合は終了
    return @books unless params[:keyword].present?

    # デバックログ出力するために記述
    Amazon::Ecs.debug = true

    begin
      # Amazon::Ecs::Responceオブジェクトの取得
      search_result = Amazon::Ecs.item_search(
        params[:keyword],
        search_index:  'Books',
        dataType: 'script',
        response_group: 'ItemAttributes, Images',
        country:  'jp',
        power: "Not kindle"
        )
    rescue Amazon::RequestError => e
      puts e
      retry
    end

    # 本のタイトル,画像URL, 詳細ページURLの取得
    search_result.items.each do |item|
      book = Book.new(
        title: item.get('ItemAttributes/Title'),
        image_url: item.get('LargeImage/URL'),
        detail_url: item.get('DetailPageURL'),
        author: item.get('ItemAttributes/Author'),
        publisher: item.get('ItemAttributes/Publisher')
        )
      @books << book
    end
  end

  private
  def create_params
    params.require(:book).permit(:title, :image_url, :detail_url, :author, :publisher).merge(user_id: current_user.id)
  end

  def registration_params
    params.require(:book).permit(:title, :image_url, :detail_url, :author, :publisher)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_list.html.erb
<% if @books.present? %>
  <% @books.each do |book| %>
    <div class="col-xs-6 col-lg-4">
      <div class="book_list">
        <%= link_to (image_tag(book.image_url)), book.detail_url %><br><hr>
        <%= book.title %><br><hr>
        <%= form_for book, url: req_books_path do |f| %>
          <%= f.hidden_field :id %>
          <%= f.hidden_field :title %>
          <%= f.hidden_field :image_url %>
          <%= f.hidden_field :detail_url %>
          <%= f.hidden_field :author %>
          <%= f.hidden_field :publisher %>
          <%= f.hidden_field :user_id %>
          <%= f.submit 'リクエスト', class: :button if user_signed_in? %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/books/_search_result.html.erb
<% if @books.present? %>
  <% @books.each do |book| %>
    <div class="col-xs-6 col-lg-4">
      <div class="book_list">
          <%= link_to (image_tag(book.image_url)), book.detail_url %><br><hr>
        <%= book.title %><br><hr>
        <%= form_for book, url: registration_books_path do |f| %>
          <%= f.hidden_field :title %>
          <%= f.hidden_field :image_url %>
          <%= f.hidden_field :detail_url %>
          <%= f.hidden_field :author %>
          <%= f.hidden_field :publisher %>
          <%= f.submit '登録', class: :button %>
      <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/books/create.html.erb
<p>本の登録が完了しました！</p>
<%= link_to(image_tag(@book.image_url, style: "width:70px;height: 100px;"), @book.detail_url) %>
<%= @book.title %><br>
<%= @book.author %><br>
<%= @book.publisher %><br>
<%= link_to '一覧画面に戻る', books_path %>

app/views/books/index.html.erb
<h2>書籍一覧</h2>
<% if @books.present? %>
  <div class="row">
    <!-- 取得した書籍を表示 -->
    <%= render partial: 'book_list' %>
  </div>
  <% else %>
    <div class="row">
      <p>書籍が登録されていません。</p>
    </div>
<% end %>

app/views/books/registration.html.erb
<%= link_to (image_tag(@book.image_url, style: "width: 70px;height: 100px;display: inline-block;")), @book.detail_url %><br>
<%= @book.title %><br>
<%= @book.author %><br>
<%= @book.publisher %><br>
<%= form_for @book, url: books_path do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :image_url %>
  <%= f.hidden_field :detail_url %>
  <%= f.hidden_field :author %>
  <%= f.hidden_field :publisher %>
  <%= f.submit 'この本を登録する！' %>
<% end %>

app/views/books/search.html.erb
<div id="search-box">
  <%= form_tag('/books/search', method: :get) do %>
  <%= text_field_tag :book, "",  id: "book_search", name: "keyword", placeholder: "キーワードを打ち込んでください", style: "width: 200px;"%><button title="検索" type="submit">検索</button>
  <% end %>
</div>
<% if @books.present? %>
<h2>検索結果</h2>
<div class="row">
  <!-- 取得した書籍を表示 -->
  <%= render partial: 'search_result' %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookShare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Freelancer - Start Bootstrap Theme</title>

  <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/freelancer.css" rel="stylesheet">

  <!-- Original CSS -->
  <link href="my.css" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- jQuery -->
  <script src="js/jquery.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
  <script src="js/classie.js"></script>
  <script src="js/cbpAnimatedHeader.js"></script>

  <!-- Contact Form JavaScript -->
  <script src="js/jqBootstrapValidation.js"></script>
  <script src="js/contact_me.js"></script>

  <!-- Custom Theme JavaScript -->
  <script src="js/freelancer.js"></script>

</head>
<body id="page-top" class="index">

  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#page-top">Book Share</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li class="page-scroll">
            <a href="/users/<%= current_user.id %>">マイページ</a>
          </li>
          <li class="page-scroll">
            <a href="/books/search">本の登録</a>
          </li>
          <li class="page-scroll">
            <%= link_to 'ログアウト', "/users/sign_out", method: :delete %>
          </li>
          <% else %>
          <li class="page-scroll">
          <%= link_to 'ログイン', "/users/sign_in" %>
          </li>
          <% end %>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>

  <div class="container" style="margin-top: 130px">
    <%= yield %>
  </div>

</body>
</html>